# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [alpha]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Alpha API
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.IP}}
          username: ubuntu
          key: ${{secrets.SSH_AWS_KEY}}
          sync: true
          timeout: 30s
          port: 22
          script: |
            node -v
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20.10.0
            nvm alias default 20.10.0
            cd BotPanel-API
            git fetch origin
            git reset --hard
            git checkout alpha
            git merge origin/alpha
            npm i
            pm2 restart api
